version: '3'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./datasets:/app/datasets
      - ./cache:/app/cache
      - ./soundfonts:/app/soundfonts
    environment:
      - FLASK_APP=web/app.py
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped 