"""Optional source-structure prior for melodic phrase part selection.

The prior reranks candidates already generated by the aligned indexed detector.
It does not create candidates or change recurrence evidence. Track names,
channels, programs and source track numbers are deliberately excluded from all
features. The resulting order is a part-role preference, not evidence that a
phrase is memorable or correct.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from hashlib import sha256
import heapq
import json
import math
import statistics
from typing import Iterable

from . import aligned as _aligned
from .aligned_indexed import detect_indexed_part
from .closed_patterns import CLOSED_PATTERN_VERSION, prefer_closed_exact_extension
from .midi import MidiSong, Note, Part


PART_PRIOR_VERSION = "source-structure-part-prior-v1"
FEATURE_VERSION = "part-structure-features-v1"
ALGORITHM_NAME = "aligned_melody"


@dataclass(frozen=True)
class PartPriorConfig:
    """Weights for a bounded additive adjustment to recurrence score."""

    name: str
    strength: float
    onset_monophony: float
    voice_independence: float
    density_fit: float
    continuity: float
    register: float
    mobility: float
    density_target: float = 2.0
    continuity_gap_beats: float = 2.0
    onset_merge_beats: float = 1 / 24

    def __post_init__(self) -> None:
        numeric = asdict(self)
        numeric.pop("name")
        if not isinstance(self.name, str) or not self.name:
            raise ValueError("name must be a nonempty string")
        if any(
            isinstance(value, bool)
            or not isinstance(value, (int, float))
            or not math.isfinite(value)
            for value in numeric.values()
        ):
            raise ValueError("part prior values must be finite numbers")
        weights = self.weights()
        if self.strength < 0 or self.strength > 0.20:
            raise ValueError("strength must be between 0 and 0.20")
        if any(value < 0 for value in weights.values()):
            raise ValueError("part prior weights must be nonnegative")
        if self.strength and not math.isclose(sum(weights.values()), 1.0, abs_tol=1e-9):
            raise ValueError("nonzero part prior weights must sum to one")
        if not self.strength and any(weights.values()):
            raise ValueError("zero-strength prior must have zero weights")
        if self.density_target <= 0 or self.continuity_gap_beats <= 0:
            raise ValueError("density target and continuity gap must be positive")
        if not 0 < self.onset_merge_beats <= 0.25:
            raise ValueError("onset merge must be in (0, 0.25]")

    def weights(self) -> dict[str, float]:
        return {
            "onset_monophony": self.onset_monophony,
            "voice_independence": self.voice_independence,
            "density_fit": self.density_fit,
            "continuity": self.continuity,
            "register": self.register,
            "mobility": self.mobility,
        }


def _preset(
    name: str,
    strength: float,
    weights: tuple[float, float, float, float, float, float],
) -> PartPriorConfig:
    return PartPriorConfig(name, strength, *weights)


# These alternatives are declared before the POP909 development fit. The fit
# may select one complete preset. It does not optimize individual coefficients.
PRESET_CONFIGS: tuple[PartPriorConfig, ...] = (
    _preset("none", 0.0, (0, 0, 0, 0, 0, 0)),
    _preset("monophony_weak", 0.04, (0.65, 0.35, 0, 0, 0, 0)),
    _preset("monophony", 0.08, (0.65, 0.35, 0, 0, 0, 0)),
    _preset("structure_weak", 0.04, (0.35, 0.25, 0.20, 0.10, 0, 0.10)),
    _preset("structure", 0.08, (0.35, 0.25, 0.20, 0.10, 0, 0.10)),
    _preset("balanced_weak", 0.04, (0.30, 0.20, 0.20, 0.10, 0.10, 0.10)),
    _preset("balanced", 0.08, (0.30, 0.20, 0.20, 0.10, 0.10, 0.10)),
    _preset("register_weak", 0.04, (0.25, 0.20, 0.15, 0.10, 0.20, 0.10)),
)
MELODY_PRIOR_CONFIG = next(config for config in PRESET_CONFIGS if config.name == "monophony")


def preset_by_name(name: str) -> PartPriorConfig:
    for config in PRESET_CONFIGS:
        if config.name == name:
            return config
    raise ValueError(f"unknown part prior preset: {name}")


def _onset_groups(notes: list[Note], ppq: int, merge_beats: float) -> list[list[Note]]:
    ordered = sorted(notes, key=lambda note: (note.start, note.pitch, note.end, note.velocity))
    groups: list[list[Note]] = []
    index = 0
    tolerance = merge_beats * ppq
    while index < len(ordered):
        end = index + 1
        while end < len(ordered) and ordered[end].start - ordered[index].start <= tolerance:
            end += 1
        groups.append(ordered[index:end])
        index = end
    return groups


def part_structure_features(
    part: Part,
    ticks_per_beat: int,
    *,
    density_target: float = 2.0,
    continuity_gap_beats: float = 2.0,
    onset_merge_beats: float = 1 / 24,
) -> dict[str, float]:
    """Return bounded note-structure features without part metadata labels."""
    if isinstance(ticks_per_beat, bool) or not isinstance(ticks_per_beat, int) or ticks_per_beat < 1:
        raise ValueError("ticks_per_beat must be a positive integer")
    for value, label in (
        (density_target, "density_target"),
        (continuity_gap_beats, "continuity_gap_beats"),
        (onset_merge_beats, "onset_merge_beats"),
    ):
        if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value) or value <= 0:
            raise ValueError(f"{label} must be a finite positive number")
    notes = list(part.notes)
    if not notes:
        return {name: 0.0 for name in PartPriorConfig(
            "empty", 0, 0, 0, 0, 0, 0, 0
        ).weights()}
    groups = _onset_groups(notes, ticks_per_beat, onset_merge_beats)
    group_starts = [min(note.start for note in group) for group in groups]
    skyline_pitches = [max(note.pitch for note in group) for group in groups]
    onset_monophony = len(groups) / len(notes)
    active_voices = []
    ordered = sorted(notes, key=lambda note: (note.start, note.end, note.pitch))
    ends: list[int] = []
    note_index = 0
    for tick in group_starts:
        while note_index < len(ordered) and ordered[note_index].start <= tick:
            heapq.heappush(ends, ordered[note_index].end)
            note_index += 1
        while ends and ends[0] <= tick:
            heapq.heappop(ends)
        active_voices.append(len(ends))
    mean_excess_voices = statistics.mean(max(0, count - 1) for count in active_voices)
    voice_independence = 1 / (1 + mean_excess_voices)
    start = min(note.start for note in notes)
    end = max(note.end for note in notes)
    span_beats = max(1 / ticks_per_beat, (end - start) / ticks_per_beat)
    density = len(groups) / span_beats
    density_fit = 1 / (1 + abs(math.log2(max(density, 1e-12) / density_target)))
    gaps = [
        (right - left) / ticks_per_beat
        for left, right in zip(group_starts, group_starts[1:])
    ]
    continuity = (
        sum(gap <= continuity_gap_beats for gap in gaps) / len(gaps)
        if gaps
        else 0.0
    )
    register = statistics.median(note.pitch for note in notes) / 127
    mobility = (
        sum(left != right for left, right in zip(skyline_pitches, skyline_pitches[1:]))
        / (len(skyline_pitches) - 1)
        if len(skyline_pitches) > 1
        else 0.0
    )
    values = {
        "onset_monophony": onset_monophony,
        "voice_independence": voice_independence,
        "density_fit": density_fit,
        "continuity": continuity,
        "register": register,
        "mobility": mobility,
    }
    return {name: round(min(1.0, max(0.0, value)), 8) for name, value in values.items()}


def score_part_features(features: dict[str, float], config: PartPriorConfig) -> float:
    expected = set(config.weights())
    if set(features) != expected:
        raise ValueError("part feature keys differ from the configured feature set")
    if any(
        isinstance(value, bool)
        or not isinstance(value, (int, float))
        or not math.isfinite(value)
        or not 0 <= value <= 1
        for value in features.values()
    ):
        raise ValueError("part features must be finite values in [0, 1]")
    return round(sum(config.weights()[name] * features[name] for name in expected), 8)


def song_part_scores(
    song: MidiSong, config: PartPriorConfig
) -> tuple[dict[int, float], dict[int, dict[str, float]]]:
    """Score each nondrum part by note structure only."""
    features: dict[int, dict[str, float]] = {}
    scores: dict[int, float] = {}
    for part in song.parts:
        if part.is_drum:
            continue
        if part.index in features:
            raise ValueError("part indices must be unique")
        row = part_structure_features(
            part,
            song.ticks_per_beat,
            density_target=config.density_target,
            continuity_gap_beats=config.continuity_gap_beats,
            onset_merge_beats=config.onset_merge_beats,
        )
        features[part.index] = row
        scores[part.index] = score_part_features(row, config)
    return scores, features


def _ranking_key(candidate: dict, part_scores: dict[int, float], strength: float) -> tuple:
    part_index = candidate.get("part_index")
    recurrence = candidate.get("recurrence_score")
    if part_index not in part_scores:
        raise ValueError("candidate refers to an unavailable nondrum part")
    if isinstance(recurrence, bool) or not isinstance(recurrence, (int, float)) or not math.isfinite(recurrence):
        raise ValueError("candidate recurrence_score must be finite")
    adjusted = float(recurrence) + strength * (part_scores[part_index] - 0.5)
    return (
        -adjusted,
        -float(recurrence),
        -candidate["note_count"],
        candidate["part_index"],
        candidate["start_tick"],
        candidate["family_id"],
    )


def _adjusted_score(candidate: dict, part_scores: dict[int, float], strength: float) -> float:
    return float(candidate["recurrence_score"]) + strength * (
        part_scores[candidate["part_index"]] - 0.5
    )


def _ordered_candidate_evidence(
    ordered: list[dict], part_scores: dict[int, float], strength: float
) -> tuple[list[dict], str]:
    rows = [
        {
            "candidate_rank": rank,
            "family_id": candidate["family_id"],
            "part_index": candidate["part_index"],
            "start_tick": candidate["start_tick"],
            "end_tick": candidate["end_tick"],
            "note_count": candidate["note_count"],
            "recurrence_score": candidate["recurrence_score"],
            "part_score": part_scores[candidate["part_index"]],
            "adjusted_score": round(
                _adjusted_score(candidate, part_scores, strength), 8
            ),
        }
        for rank, candidate in enumerate(ordered, 1)
    ]
    payload = json.dumps(
        rows, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False
    ).encode("utf-8")
    return rows, sha256(payload).hexdigest()


def select_part_ranked_closed_candidates(
    candidates: Iterable[dict],
    song: MidiSong,
    config: PartPriorConfig,
    *,
    top_k: int = 3,
) -> tuple[list[dict], dict]:
    """Rerank the existing shortlist then apply frozen closed selection rules."""
    if isinstance(top_k, bool) or not isinstance(top_k, int) or top_k < 1:
        raise ValueError("top_k must be a positive integer")
    rows = list(candidates)
    part_scores, features = song_part_scores(song, config)
    ordered = sorted(rows, key=lambda row: _ranking_key(row, part_scores, config.strength))
    ordered_evidence, candidate_order_sha256 = _ordered_candidate_evidence(
        ordered, part_scores, config.strength
    )
    evidence_by_identity = {
        id(candidate): row for candidate, row in zip(ordered, ordered_evidence)
    }
    selected: list[dict] = []
    replacements: list[dict] = []
    for prior_rank, candidate in enumerate(ordered, 1):
        redundant_index = next(
            (
                index
                for index, prior in enumerate(selected)
                if _aligned._redundant(candidate, prior)
            ),
            None,
        )
        if redundant_index is None:
            selected.append(candidate)
        else:
            prior = selected[redundant_index]
            boundary_extension = _aligned._prefer_boundary_extension(candidate, prior)
            closed_extension = prefer_closed_exact_extension(candidate, prior)
            if boundary_extension or closed_extension:
                selected[redundant_index] = candidate
                replacements.append(
                    {
                        "rank": prior_rank,
                        "selected_index": redundant_index,
                        "replaced_family_id": prior["family_id"],
                        "replacement_family_id": candidate["family_id"],
                        "boundary_extension": boundary_extension,
                        "closed_extension": closed_extension,
                    }
                )
        if len(selected) == top_k:
            break
    evidence = {
        "version": PART_PRIOR_VERSION,
        "feature_version": FEATURE_VERSION,
        "config": asdict(config),
        "candidate_count": len(rows),
        "top_k": top_k,
        "reranks_full_shortlist": True,
        "closed_selection": CLOSED_PATTERN_VERSION,
        "part_scores": {str(key): value for key, value in sorted(part_scores.items())},
        "part_features": {str(key): value for key, value in sorted(features.items())},
        "candidate_order_sha256": candidate_order_sha256,
        "selected_family_ids": [candidate["family_id"] for candidate in selected],
        "selected": [
            {**evidence_by_identity[id(candidate)], "selected_index": selected_index}
            for selected_index, candidate in enumerate(selected)
        ],
        "replacements": replacements,
    }
    return selected, evidence


def extract_part_ranked(
    song: MidiSong, cfg: _aligned.AlignedConfig | None = None
) -> dict:
    """Extract with the indexed shortlist and fixed optional melody prior."""
    cfg = cfg or _aligned.AlignedConfig()
    if not isinstance(cfg, _aligned.AlignedConfig):
        raise TypeError("cfg must be an AlignedConfig")
    candidates: list[dict] = []
    stats: list[dict] = []
    for part in song.parts:
        found, audit = detect_indexed_part(song, part, cfg)
        candidates.extend(found)
        stats.append(audit)
    phrases, evidence = select_part_ranked_closed_candidates(
        candidates, song, MELODY_PRIOR_CONFIG, top_k=cfg.top_k
    )
    limit_keys = (
        "note_limit_reached",
        "window_limit_reached",
        "comparison_limit_reached",
        "group_limit_reached",
    )
    return {
        "config": asdict(cfg),
        "algorithm": ALGORITHM_NAME,
        "selection": PART_PRIOR_VERSION,
        "part_ranking": evidence,
        "phrases": phrases,
        "candidate_count": len(candidates),
        "raw_repeat_group_count": sum(part["repeat_groups"] for part in stats),
        "shortlisted_candidate_count": len(candidates),
        "curation_truncated": any(part["candidate_limit_reached"] for part in stats),
        "search_limited": any(
            any(part[key] for key in limit_keys) or part["saturated_seed_buckets"]
            for part in stats
        ),
        "part_stats": stats,
        "index_variant": "exact_first_cached_v1",
    }
